[package]
name = "git_panel"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[lib]
path = "src/git_panel.rs"
doctest = false

[dependencies]
anyhow.workspace = true
git.workspace = true
gpui.workspace = true
project.workspace = true
ui.workspace = true
workspace.workspace = true
