[package]
name = "debugger_tools"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/debugger_tools.rs"
doctest = false

[dependencies]
gpui.workspace = true
workspace.workspace = true
editor.workspace = true
project.workspace = true
dap.workspace = true
serde_json.workspace = true
futures.workspace = true
anyhow.workspace = true
